spring:
  profiles:
    active: test
  jpa:
    open-in-view: false
  #Nome da Aplica��o
  application:
    name: ms-pedidos


#LocalHost que o eureka server esta recebendo as requisi��es
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#Define a porta do servi�o
server:
  port: 0
